[workspace]
resolver = "3"
members = [
    "cli",
    "csar",
    "tosca",
    "sdk",
    "plugin",
    "python",
    "examples/plugins/kubernetes",
]

[profile.release]
strip = "debuginfo"
lto = true
